/* =========================================================
   RESERVED LA — Site config + product catalog
   ========================================================= */

const BRAND = {
  name: "RESERVED LA",
  legalName: "ZA Distribution LLC",
  dba: "Reserved LA is a DBA of ZA Distribution LLC",
  ein: "88-1123884",
  email: "support@reservedla.com",
  phone: "[YOUR PHONE NUMBER]",            // <-- replace before launch
  phoneHref: "tel:+1",                      // <-- replace before launch
  address1: "2930 Shawn Way",
  address2: "Rancho Cordova, California 95670",
  country: "United States",
  hours: "Customer Service: 7 days a week, 8AM–8PM PT",
  instagram: "https://www.instagram.com/reservedhollywood/",
  instagramHandle: "@reservedhollywood",
  threads: "https://www.threads.com/@reservedhollywood?xmt=AQG0-ngZoo55GiSwxFtRLDprA-D4MRIE2RD43iFKkv5hNFs",
  threadsHandle: "@reservedhollywood",
  freeShipThreshold: 150,
  currency: "USD"
};

/* ---- Branded SVG placeholder generator (crisp, on-brand, swappable) ---- */
function phSvg(label, sub, opts){
  opts = opts || {};
  const bg = opts.bg || "#17150f";
  const fg = opts.fg || "#f5f2ec";
  const w = opts.w || 800, h = opts.h || 1000;
  const big = (sub || "").toUpperCase();
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}' viewBox='0 0 ${w} ${h}'>
  <defs>
    <pattern id='p' width='34' height='34' patternTransform='rotate(45)' patternUnits='userSpaceOnUse'>
      <rect width='34' height='34' fill='${bg}'/>
      <line x1='0' y1='0' x2='0' y2='34' stroke='${fg}' stroke-opacity='0.05' stroke-width='2'/>
    </pattern>
    <linearGradient id='g' x1='0' y1='0' x2='0' y2='1'>
      <stop offset='0' stop-color='${bg}'/><stop offset='1' stop-color='#000'/>
    </linearGradient>
  </defs>
  <rect width='${w}' height='${h}' fill='url(#g)'/>
  <rect width='${w}' height='${h}' fill='url(#p)'/>
  <text x='50%' y='16%' fill='${fg}' fill-opacity='0.5' font-family="Arial,Helvetica,sans-serif" font-size='20' font-weight='700' letter-spacing='8' text-anchor='middle'>RESERVED LA</text>
  <text x='50%' y='50%' fill='${fg}' font-family="Arial Narrow,Impact,sans-serif" font-size='${Math.min(150, 1300/Math.max(big.length,4))}' font-weight='900' letter-spacing='2' text-anchor='middle' dominant-baseline='middle'>${big}</text>
  <text x='50%' y='90%' fill='${fg}' fill-opacity='0.6' font-family="Arial,Helvetica,sans-serif" font-size='22' font-weight='600' letter-spacing='3' text-anchor='middle'>${(label||"").toUpperCase()}</text>
</svg>`;
  return "data:image/svg+xml;utf8," + encodeURIComponent(svg);
}

/* ---- Category color themes for placeholders ---- */
const CAT_BG = {
  "Hoodies":"#17150f", "T-Shirts":"#1a1a1a", "Jackets":"#12140f",
  "Denim":"#141821", "Bottoms":"#1b1712", "Headwear":"#161311", "Accessories":"#181818"
};

/* ---- Product catalog ---- */
const PRODUCTS = [

  /* ---- Shorts collection (real photography, verified logo-free) ---- */
  {id:"rl-sp260310pmh6", name:"Light Wash Distressed Denim Shorts", cat:"Shorts", price:70, was:0, color:"Light Wash", tag:"BEST SELLER", rating:4.7, reviews:88, sizes:["S","M","L","XL","XXL"], oos:["S","XXL"], photos:["rl-sp260310pmh6-front.jpg","rl-sp260310pmh6-side.jpg","rl-sp260310pmh6-back.jpg","rl-sp260310pmh6-detail.jpg"], story:["The Light Wash Distressed Denim Shorts take a relaxed wide-leg jort and push it into full streetwear territory, cut long and loose for an easy, lived-in drape. A bright light wash and all-over crackle give them a sun-faded look straight off the rack.","Heavy hand-finished rips run across the front and open into an irregular frayed hem that keeps fraying with every wear. Classic five-pocket construction, antique rivets and a signature Reserved LA woven tab finish a pair built to look better the more you beat them up."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed wide-leg fit","Falls below the knee","Heavy distressing and blown-out rips","Raw, irregular frayed hem","Five-pocket styling with antique rivets","Reserved LA woven tab at back pocket","100% cotton denim"], desc:"Loose wide-leg denim jorts in a light wash, finished with heavy rips and an irregular frayed hem for real streetwear grit."},
  {id:"rl-sp26061297av", name:"Camo 3/4 Cargo Shorts", cat:"Shorts", price:86, was:0, color:"Green Camo", tag:"NEW", rating:4.8, reviews:42, sizes:["S","M","L","XL"], oos:[], photos:["rl-sp26061297av-front.jpg","rl-sp26061297av-side.jpg","rl-sp26061297av-back.jpg","rl-sp26061297av-detail.jpg"], story:["Cut in a longer 3/4 length, the Camo 3/4 Cargo Shorts sit right at the shin for that oversized, early-2000s utility silhouette. A soft washed camo print with tonal contrast stitching keeps them looking broken-in from day one.","Bellowed flap cargo pockets ride each leg for real storage, reinforced with bar-tack stitching at every stress point. Cut from durable cotton ripstop with a relaxed straight leg, they layer effortlessly over any sneaker."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed straight fit","Longer 3/4 length","Bellowed flap cargo pockets","Bar-tack reinforced stress points","Washed camo print","Reserved LA woven tab","100% cotton ripstop"], desc:"Cotton ripstop camo cargos in a longer 3/4 length. Relaxed straight fit, reinforced flap pockets, and bar-tack stitching at the stress points."},
  {id:"rl-sp260616fa60", name:"Military Wide-Leg Cargo Shorts", cat:"Shorts", price:92, was:0, color:"Washed Camo", tag:"NEW", rating:4.8, reviews:61, sizes:["S","M","L","XL","XXL"], oos:["XXL"], photos:["rl-sp260616fa60-front.jpg","rl-sp260616fa60-side.jpg","rl-sp260616fa60-back.jpg","rl-sp260616fa60-detail.jpg"], story:["The Military Wide-Leg Cargo Shorts are our most dramatic short yet — cut wide and long with true volume through the leg for a runway-ready, utilitarian shape. A vintage camo wash with rust-toned overdye gives every pair a weathered, one-of-one feel.","Stacked utility pockets, webbing straps and buckle hardware bring genuine military detailing, while adjustable leg tabs let you tune the drape. Built from heavy washed cotton that holds its structure and softens with wear."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Wide-leg volume fit","Long, below-knee length","Stacked cargo and utility pockets","Webbing straps with buckle hardware","Adjustable leg tabs","Vintage camo overdye wash","100% heavy cotton"], desc:"Wide-leg military cargos in a vintage-washed camo, cut long and roomy with stacked utility pockets, webbing straps and buckle detailing. A dramatic, runway-ready short."},
  {id:"rl-sp260602ah0q", name:"Cargo Multi-Pocket Denim Jorts", cat:"Shorts", price:72, was:88, color:"Washed Denim", tag:"SALE", rating:4.6, reviews:64, sizes:["M","L","XL","XXL"], oos:["M"], photos:["rl-sp260602ah0q-front.jpg","rl-sp260602ah0q-side.jpg","rl-sp260602ah0q-back.jpg","rl-sp260602ah0q-detail.jpg"], story:["Part cargo, part jort — the Cargo Multi-Pocket Denim Jorts combine a wide denim base with utility pockets stacked down each leg. A mid washed indigo keeps them versatile enough to anchor any fit.","Flap cargo pockets, coin pockets and classic five-pocket denim styling give you storage from every angle, all reinforced with sturdy rivets. A frayed cut hem adds the finishing streetwear edge."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed wide fit","Below-knee length","Stacked flap cargo pockets","Five-pocket denim construction","Reinforced rivets","Frayed cut hem","100% cotton denim"], desc:"Cotton denim cargo jorts with a soft wash, wide-leg silhouette, raw hem, and a reinforced multi-pocket layout. Utility with an attitude."},
  {id:"rl-sp260514qcbq", name:"Industrial Cargo Shorts", cat:"Shorts", price:116, was:0, color:"Washed Brown", tag:"", rating:4.9, reviews:37, sizes:["M","L","XL","XXL"], oos:["M"], photos:["rl-sp260514qcbq-front.jpg","rl-sp260514qcbq-side.jpg","rl-sp260514qcbq-back.jpg","rl-sp260514qcbq-detail.jpg"], story:["The Industrial Cargo Shorts are our most technical short yet, built on a washed-brown canvas with contrast black mesh panels and a full rig of straps, buckles and D-rings. Rust-toned overdye and heavy topstitching give every pair a weathered, one-of-one feel.","Stacked 3D cargo pockets, webbing straps, metal eyelets and adjustable buckle hardware make them as functional as they are aggressive — genuine utility with a runway edge. Cut from a heavy washed cotton canvas with mesh inserts and a relaxed straight leg."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed straight fit","Washed-brown canvas with black mesh panels","Stacked 3D cargo pockets","Webbing straps with buckle hardware","Metal eyelets and D-rings","Rust-toned overdye wash","Heavy washed cotton canvas"], desc:"Heavy washed-canvas cargo shorts with 3D utility pockets, mesh panels, and a full rig of straps and buckle hardware. A premium, hard-edged statement."},
  {id:"rl-sp2607079rsc", name:"Drawstring Distressed Shorts", cat:"Shorts", price:82, was:0, color:"Washed Brown", tag:"", rating:4.7, reviews:49, sizes:["S","M","L","XL","XXL"], oos:["S"], photos:["rl-sp2607079rsc-front.jpg","rl-sp2607079rsc-side.jpg","rl-sp2607079rsc-back.jpg","rl-sp2607079rsc-detail.jpg"], story:["The Drawstring Distressed Shorts blend rugged utility with an easy drawcord waist, built on a washed-brown canvas with rust-toned overdye and heavy hand-thrashed distressing. Blown-out rips and a cracked wash give every pair a genuinely worn-in, one-of-one look.","Cargo flap pockets, webbing straps, buckle hardware and metal eyelets stack down each leg for real function and attitude, while the elasticated drawcord waist keeps them comfortable. Cut from a heavy washed cotton canvas with a relaxed, roomy leg."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed roomy fit","Elasticated drawcord waist","Washed-brown canvas with rust overdye","Heavy hand-thrashed rips","Cargo flap pockets with buckle straps","Metal eyelets and D-rings","Heavy washed cotton canvas"], desc:"Heavy washed-canvas drawstring shorts with blown-out distressing, cargo pockets, and buckle-strap hardware. Rugged utility with a lived-in, premium finish."},
  {id:"rl-sp250320sflm", name:"Zipper Slit Denim Jorts", cat:"Shorts", price:68, was:0, color:"Off White", tag:"", rating:4.6, reviews:58, sizes:["M","L","XL","XXL","XXXL"], oos:[], photos:["rl-sp250320sflm-front.jpg","rl-sp250320sflm-side.jpg","rl-sp250320sflm-back.jpg","rl-sp250320sflm-detail.jpg"], story:["The Zipper Slit Denim Jorts land in a clean off-white wash, cut long below the knee for that oversized, drop-hem jort silhouette. Exposed metal zips run up the outer leg, opening into dramatic side vents that shift the shape as you move.","A heavy hand-cut frayed hem and classic five-pocket styling keep them grounded in heritage denim, while the full-length zips add an elevated, deconstructed edge. Cut from a rigid cotton denim that holds its structure and frays in beautifully."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Relaxed, long below-knee fit","Off-white denim wash","Functional exposed side zips","Dramatic zip slit vents","Heavy hand-cut frayed hem","Classic five-pocket styling","100% cotton denim"], desc:"Long off-white denim jorts with functional exposed side zips, dramatic slit vents, and a heavy frayed hem. A clean, deconstructed statement."},

  /* ---- Denim / Jackets / Hoodies / Bottoms (real photography, verified logo-free) ---- */
  {id:"rl-sp230804mvtd", name:"Baggy Multi-Pocket Cargo Jeans", cat:"Denim", price:118, was:0, color:"Washed Olive", tag:"NEW", rating:4.8, reviews:64, sizes:["M","L","XL","XXL"], oos:["L"], photos:["rl-sp230804mvtd-front.jpg","rl-sp230804mvtd-side.jpg","rl-sp230804mvtd-back.jpg","rl-sp230804mvtd-detail.jpg"], story:["The Baggy Multi-Pocket Cargo Jeans deliver full baggy volume in a washed olive overdye, cut wide from waist to hem for a true early-2000s cargo silhouette. Rust-toned fading and subtle whiskering give every pair instant broken-in character.","Flap cargo pockets stack down each leg alongside classic five-pocket denim, giving you storage everywhere without breaking the wide-leg line. Built from durable cotton denim that only gets better with age."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Baggy wide-leg fit","Full length","Stacked flap cargo pockets","Five-pocket construction","Washed olive overdye","Reserved LA woven tab","100% cotton denim"], desc:"Baggy multi-pocket cargo jeans in a washed olive overdye. A stack of utility pockets and a huge wide-leg drape. Peak baggy cargo denim."},
  {id:"rl-sp251013gasp", name:"Washed Workwear Barrel Jeans", cat:"Denim", price:124, was:0, color:"Washed Olive", tag:"BEST SELLER", rating:4.8, reviews:97, sizes:["M","L","XL","XXL"], oos:[], photos:["rl-sp251013gasp-front.jpg","rl-sp251013gasp-side.jpg","rl-sp251013gasp-back.jpg","rl-sp251013gasp-detail.jpg"], story:["The Washed Workwear Barrel Jeans pair a heavy carpenter build with a washed-olive overdye and a subtle tonal monogram for a warm, earthy, broken-in look. Cut wide and roomy through the leg, they land squarely in workwear-baggy territory.","Utility hammer-loop pockets, paneled knees, contrast topstitching and hard-wearing rivets bring genuine jobsite DNA to a fashion-forward cut. Built from a heavy cotton denim with just enough rigidity to hold the volume."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 32-inch waist — wears size M", features:["Wide, roomy workwear fit","Mid-rise","Washed-olive overdye with tonal monogram","Utility hammer-loop pockets","Paneled knees and contrast topstitching","Reserved LA woven tab","100% cotton denim"], desc:"Wide carpenter workwear jeans in a washed-olive overdye with tonal monogram. Utility pockets, paneled knees, and a broken-in hand-feel. Statement denim built to age well."},
  {id:"rl-sp251119we8r", name:"Distressed Shearling-Collar Bomber", cat:"Jackets", price:158, was:0, color:"Distressed Brown", tag:"NEW", rating:4.9, reviews:41, sizes:["S","M","L","XL"], oos:[], photos:["rl-sp251119we8r-front.jpg","rl-sp251119we8r-side.jpg","rl-sp251119we8r-back.jpg","rl-sp251119we8r-detail.jpg"], story:["The Distressed Shearling-Collar Bomber pairs a heavily distressed brown shell with a plush cream faux-shearling collar for a rugged, vintage-flight-jacket feel. Cracked, sun-bleached marbling makes every piece look seasons-old in the best way.","A full-zip front, ribbed cuffs and hem, flap chest pockets and a boxy cut keep it functional and easy to layer over knits and hoodies. Built from a washed coated-cotton shell with a faux-shearling collar and quilted lining."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Boxy, layer-ready fit","Cream faux-shearling collar","Heavily distressed marbled-brown shell","Full-zip front with flap chest pockets","Ribbed cuffs and hem","Reserved LA woven label","Coated-cotton shell, quilted lining"], desc:"Boxy bomber in a distressed marbled-brown shell with a plush cream shearling-style collar. Full-zip, warm, and vintage — winter's easiest layer."},
  {id:"rl-sp251204c5s2", name:"Patchwork Layered Hoodie", cat:"Hoodies", price:118, was:0, color:"Charcoal", tag:"NEW", rating:4.8, reviews:53, sizes:["S","M","L","XL"], oos:["XL"], photos:["rl-sp251204c5s2-hero.jpg"], story:["The Patchwork Layered Hoodie stacks contrasting charcoal panels and layered hems for a deconstructed, double-take silhouette. It looks like two pieces fused into one.","Layered construction, mixed textures and a heavyweight build give it real depth and structure. Cut from a brushed cotton-blend fleece for warmth and drape."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized boxy fit","Layered, patchwork panels","Double-hem detailing","Kangaroo pocket","Ribbed cuffs and hem","Reserved LA woven label","Cotton-blend fleece"], desc:"Two-tone patchwork hoodie with a layered raw-edge hem, distressed detailing, and a heavyweight brushed-back interior. Oversized and lived-in."},
  {id:"rl-sp260302osst", name:"Studded Utility Cargo Pants", cat:"Bottoms", price:98, was:0, color:"Field Olive", tag:"", rating:4.7, reviews:38, sizes:["S","M","L","XL","XXL"], oos:["M","XXL"], photos:["rl-sp260302osst-hero.jpg"], story:["The Studded Utility Cargo Pants turn up the hardware, mixing field-olive cargo styling with metal studs and technical strapping for a bold, edgy statement. Utility meets punk energy.","Stacked cargo pockets, adjustable straps and stud detailing add function and attitude, while the relaxed straight leg keeps it wearable. Built from durable cotton twill."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed straight fit","Stacked cargo pockets","Metal stud detailing","Adjustable side straps","Field-olive finish","Reserved LA woven tab","100% cotton twill"], desc:"Heavyweight utility cargo pants in a faded field olive, finished with decorative stud work and roomy flap pockets. Straight-leg, workwear-built."},
  {id:"rl-sp260311wpc1", name:"Rope-Detail Wide-Leg Sweatpants", cat:"Bottoms", price:88, was:0, color:"Heather Grey", tag:"", rating:4.7, reviews:59, sizes:["S","M","L","XL"], oos:["M"], photos:["rl-sp260311wpc1-hero.jpg"], story:["The Rope-Detail Wide-Leg Sweatpants bring an elevated, drapey take on loungewear, cut wide with a chunky rope drawcord for a soft, sculptural waist. Heather grey keeps them endlessly wearable.","A wide, flowing leg and brushed-back fleece deliver serious comfort without looking basic. Made from a heavyweight cotton-blend French terry that keeps its shape."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Wide-leg fit","Chunky rope drawcord","Elasticated waist","Brushed-back fleece","Side pockets","Reserved LA woven tab","Cotton-blend French terry"], desc:"Wide-leg heavyweight sweatpants with a chunky decorative rope drawcord and a rounded barrel leg. Elevated loungewear with a sculptural shape."},
  {id:"rl-sp251117fbbn", name:"Pinstripe Pleated Wide-Leg Pants", cat:"Bottoms", price:92, was:0, color:"Charcoal Pinstripe", tag:"NEW", rating:4.7, reviews:44, sizes:["S","M","L","XL","XXL"], oos:["XXL"], photos:["rl-sp251117fbbn-hero.jpg"], story:["The Pinstripe Pleated Wide-Leg Pants take tailoring into streetwear, pairing a charcoal pinstripe with sharp front pleats and a wide, flowing leg. Dressed-up looks with a relaxed attitude.","Front pleats add volume and drape, while a clean waistband and slant pockets keep the lines tailored. Cut from a smooth wool-blend suiting fabric."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 32-inch waist — wears size M", features:["Wide-leg fit","Front-pleated","Charcoal pinstripe","Clean tailored waistband","Slant side pockets","Reserved LA woven tab","Wool-blend suiting"], desc:"Pleated wide-leg trousers in a tonal pinstripe with a dramatic barrel silhouette. Tailored on top, voluminous through the leg."},
  {id:"rl-sp2601263vsl", name:"Drawstring Wide-Leg Sweatpants", cat:"Bottoms", price:84, was:0, color:"Heather Grey", tag:"", rating:4.6, reviews:71, sizes:["S","M","L","XL"], oos:[], photos:["rl-sp2601263vsl-hero.jpg"], story:["The Drawstring Wide-Leg Sweatpants are a wardrobe workhorse — wide, comfortable and cut in an easy heather grey. Built for lounging and layering with equal ease.","An elasticated drawcord waist and roomy leg keep them relaxed, while brushed fleece adds warmth. Made from a heavyweight cotton-blend fleece that holds its shape wash after wash."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Wide-leg fit","Elasticated drawcord waist","Brushed-back fleece","Side pockets","Ribbed ankle option","Reserved LA woven tab","Cotton-blend fleece"], desc:"Relaxed wide-leg sweatpants in soft heather fleece with a clean drawstring waist. The everyday pair you'll reach for on repeat."},
  {id:"rl-sp250402sntq", name:"Pleated Drape Trousers", cat:"Bottoms", price:96, was:118, color:"Slate / Black", tag:"SALE", rating:4.7, reviews:36, sizes:["S","M","L","XL","XXL"], oos:["M"], photos:["rl-sp250402sntq-hero.jpg"], story:["The Pleated Drape Trousers deliver fluid, elevated movement with a slate-and-black tonal finish and soft front pleats. A refined piece that dresses a fit up instantly.","The pleats release into a draping wide leg, balanced by a clean waistband and side pockets. Cut from a fluid poly-blend that moves and flows."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Wide, draping leg","Front-pleated","Slate/black tonal finish","Clean waistband","Side pockets","Reserved LA woven tab","Fluid poly blend"], desc:"Pleated drape trousers with a soft woven hand and an architectural wide leg. Clean-fit waist, fluid movement — smart-casual done street."},
  {id:"rl-sp260817for3", name:"Frayed Patchwork Bomber Jacket", cat:"Jackets", price:148, was:0, color:"Washed Brown", tag:"NEW", rating:4.8, reviews:37, sizes:["S","M","L","XL"], oos:["S"], photos:["rl-sp260817for3-front.jpg","rl-sp260817for3-side.jpg","rl-sp260817for3-back.jpg","rl-sp260817for3-detail.jpg"], story:["The Frayed Patchwork Bomber Jacket splices washed-brown denim panels with heavy frayed seams and exposed raw edges for a deconstructed, artisanal bomber. A tonal crackle wash runs through the base, and every panel adds its own texture and tone.","Raw frayed seams criss-cross a boxy bomber silhouette with a full-zip front, sleeve zip pocket and ribbed trims. Cut from mixed washed cotton denim with a smooth lining for easy wear."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Boxy bomber silhouette","Washed-brown patchwork panelling","Heavy frayed, exposed seams","Full-zip front with sleeve zip pocket","Ribbed collar, cuffs and hem","Reserved LA woven label","Mixed cotton denim shell"], desc:"Boxy bomber with raw-edge patchwork seams criss-crossing a washed-brown denim body. Sleeve zip pocket, ribbed trims, statement fit."},
  {id:"rl-sp260824suyi", name:"Convertible-Collar Bomber Jacket", cat:"Jackets", price:142, was:0, color:"Heather Grey", tag:"NEW", rating:4.7, reviews:29, sizes:["M","L","XL"], oos:[], photos:["rl-sp260824suyi-hero.jpg"], story:["The Convertible-Collar Bomber Jacket is built for versatility, with a collar that zips up into a funnel neck or folds open for a cleaner look. A heather-grey finish keeps it easy to style.","A two-way front zip, snap storm flap and zip pockets add function, while the mid-weight build works across seasons. Cut from a brushed cotton blend with a smooth lining."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Regular fit","Convertible zip-up collar","Two-way front zip","Snap storm flap","Zip side pockets","Reserved LA woven label","Brushed cotton blend"], desc:"Boxy bomber in a heather cotton twill with a convertible stand collar, snap front, and elasticated hem. Clean, minimal everyday outerwear."},
  {id:"rl-sp251104soik", name:"Vintage Faded Wide Barrel Jeans", cat:"Denim", price:118, was:0, color:"Dirty Vintage Wash", tag:"BEST SELLER", rating:4.8, reviews:112, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-sp251104soik-front.jpg","rl-sp251104soik-side.jpg","rl-sp251104soik-back.jpg","rl-sp251104soik-detail.jpg"], story:["The Vintage Faded Wide Barrel Jeans go big on volume, pairing a super-wide baggy leg with a dirty vintage overdye and a subtle tonal monogram. Heavy sandblasted fading and whiskering read like a decade-old pair pulled from the archive.","The rounded barrel silhouette balloons through the thigh before curving toward the hem, grounded by paneled knees and clean five-pocket styling. Woven from a rigid cotton denim that softens into its shape over time."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Super-wide barrel leg","Mid-rise","Dirty vintage overdye with tonal monogram","Heavy sandblasted whiskering","Paneled knees","Five-pocket construction","100% cotton denim"], desc:"Super-wide barrel-leg jeans in a dirty vintage wash with tonal monogram. Rounded silhouette, paneled knees, and a genuinely broken-in finish."},
  {id:"rl-sp251117bhmv", name:"Crackle-Washed Barrel Jeans", cat:"Denim", price:116, was:0, color:"Crackle Wash", tag:"NEW", rating:4.7, reviews:64, sizes:["S","M","L","XL","XXL"], oos:["L"], photos:["rl-sp251117bhmv-front.jpg","rl-sp251117bhmv-side.jpg","rl-sp251117bhmv-back.jpg","rl-sp251117bhmv-detail.jpg"], story:["The Crackle-Washed Barrel Jeans lead with a striking marbled crackle wash — an all-over web of light-and-dark texture over a dirty tan overdye. No two pairs wear exactly alike.","The barrel cut balloons through the thigh and rounds toward the hem for a sharp, sculptural line, grounded by paneled knees, antique hardware and five-pocket styling. Built from rigid cotton denim that holds its structure."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Rounded barrel leg","Mid-rise","Marbled crackle wash over tan overdye","Paneled knees","Antique hardware","Five-pocket construction","100% cotton denim"], desc:"Barrel-cut jeans in a striking marbled crackle wash. Voluminous through the thigh with paneled knees — a real statement denim."},
  {id:"rl-sp250715s7eb", name:"Distressed Dirty-Wash Jeans", cat:"Denim", price:112, was:0, color:"Black Dirty Wash", tag:"", rating:4.6, reviews:73, sizes:["S","M","L","XL","XXL"], oos:["L"], photos:["rl-sp250715s7eb-front.jpg","rl-sp250715s7eb-side.jpg","rl-sp250715s7eb-back.jpg","rl-sp250715s7eb-detail.jpg"], story:["The Distressed Dirty-Wash Jeans lean grungy, with a black crackle overdye and muddy, lived-in fades for a genuinely worn look. Grime-toned shadows and a marbled surface give them a rebellious, broken-in feel.","Hand-placed distressing, blown-out rips and frayed openings run throughout, cut wide and baggy through the leg. Built from heavy cotton denim made to take a beating."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Baggy wide-leg fit","Full length","Black crackle dirty-wash overdye","Hand-placed distressing and rips","Frayed openings","Reserved LA woven tab","100% cotton denim"], desc:"Baggy jeans in a black crackle dirty-wash with hand-placed rips and faded whiskering. Looks like you have had them for years."},
  {id:"rl-sp250612jts0", name:"Light Wash Barrel Jeans", cat:"Denim", price:114, was:134, color:"Light Wash", tag:"SALE", rating:4.7, reviews:88, sizes:["S","M","L","XL","XXL"], oos:["M"], photos:["rl-sp250612jts0-front.jpg","rl-sp250612jts0-side.jpg","rl-sp250612jts0-back.jpg","rl-sp250612jts0-detail.jpg"], story:["The Light Wash Barrel Jeans keep it bright and clean — a pale light wash with a subtle tonal monogram over a wide barrel leg for an airy, modern denim statement. Soft fading lets the silhouette lead.","The barrel shape gives volume through the thigh and rounds toward the hem, finished with clean five-pocket styling and tonal stitching. Woven from rigid cotton denim that breaks in over time."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Wide barrel leg","Mid-rise","Bright light wash with tonal monogram","Tonal stitching","Five-pocket construction","Reserved LA woven tab","100% cotton denim"], desc:"Baggy barrel jeans in a bright light wash with soft fading. Rounded leg, cropped cuff — peak Y2K denim."},
  {id:"rl-sp260813qpa7", name:"Chunky Rib Knit Beanie", cat:"Headwear", price:32, was:0, color:"Cream / Black", tag:"BEST SELLER", rating:4.9, reviews:134, sizes:["OS"], oos:[], photos:["rl-sp260813qpa7-hero4.jpg"], story:["The Chunky Rib Knit Beanie is a cold-weather staple in a cream-and-black colourway, knit in a thick chunky rib for warmth and texture. A classic fold-up cuff keeps it timeless.","The chunky knit holds its shape and stretches to fit, while the soft yarn keeps things cozy. Made from a soft acrylic-blend rib knit."], model:"One size — fits most; the rib knit stretches to shape", features:["Fold-up cuffed beanie","Chunky rib knit","Cream / black colourway","Soft, warm hand-feel","Reserved LA woven tab","Acrylic-blend knit"], desc:"Soft chunky-rib acrylic beanie with a deep cuff. Warm, stretchy, one-size-fits-most. Shown in cream and black."},
  {id:"rl-sp260813zdsh", name:"Corduroy Slouchy Beanie", cat:"Headwear", price:30, was:0, color:"Black / Cream", tag:"NEW", rating:4.7, reviews:58, sizes:["OS"], oos:[], photos:["rl-sp260813zdsh-hero4.jpg"], story:["The Corduroy Slouchy Beanie swaps knit for soft ribbed corduroy, delivering a relaxed, slouchy shape in a black-and-cream mix. A textured twist on the classic beanie.","The slouchy cut sits back off the forehead for an easy, lived-in look, lined for comfort. Made from a soft cotton corduroy with a jersey lining."], model:"One size — slouchy fit", features:["Slouchy fit","Ribbed corduroy build","Black / cream mix","Soft jersey lining","Reserved LA woven tab","Cotton corduroy"], desc:"Lightweight corduroy-knit slouchy beanie with a longline fit. Wear it cuffed or slouched."},
  {id:"rl-sp2606081gvu", name:"Vintage Washed Dad Cap", cat:"Headwear", price:28, was:0, color:"Washed Blue / Tan", tag:"", rating:4.7, reviews:96, sizes:["OS"], oos:[], photos:["rl-sp2606081gvu-hero4.jpg"], story:["The Vintage Washed Dad Cap brings a broken-in, faded finish in a washed blue with tan detailing. The soft, unstructured crown gives it that perfectly worn dad-cap feel.","A curved brim, low profile and adjustable strap back make it an easy everyday cap. Made from garment-washed cotton twill."], model:"One size — adjustable strap back", features:["Unstructured low-profile crown","Curved brim","Vintage washed finish","Adjustable strap back","Reserved LA woven tab","Washed cotton twill"], desc:"Six-panel dad cap in a vintage washed cotton with hand-distressed edges and a curved brim. Adjustable strap back."},
  {id:"rl-sp260303bd5k", name:"Distressed Panel Cap", cat:"Headwear", price:28, was:0, color:"Washed Blue / Cream", tag:"NEW", rating:4.6, reviews:41, sizes:["OS"], oos:[], photos:["rl-sp260303bd5k-hero3.jpg"], story:["The Distressed Panel Cap mixes washed-blue and cream panels with frayed, distressed edges for a genuinely vintage feel. Worn-in character in every panel.","A structured six-panel crown, curved brim and adjustable strap keep it classic under the distressing. Made from washed cotton twill."], model:"One size — adjustable strap back", features:["Structured six-panel crown","Curved brim","Distressed panel detailing","Washed blue / cream","Adjustable strap back","Washed cotton twill"], desc:"Low-profile washed cap with a soft unstructured crown and distressed panels. Everyday, broken-in headwear."},
  {id:"rl-sp260224ui92", name:"Distressed Denim Cap", cat:"Headwear", price:30, was:0, color:"Washed Denim", tag:"", rating:4.6, reviews:52, sizes:["OS"], oos:[], photos:["rl-sp260224ui92-hero2.jpg"], story:["The Distressed Denim Cap brings washed denim to your headwear, complete with frayed brim edges and a faded finish. A denim-lover's everyday cap.","A six-panel crown, curved denim brim and adjustable strap keep it timeless. Made from washed cotton denim."], model:"One size — adjustable strap back", features:["Six-panel crown","Curved brim with frayed edges","Washed denim finish","Adjustable strap back","Reserved LA woven tab","Cotton denim"], desc:"Washed denim baseball cap with frayed distressing and contrast repair stitching. Adjustable back, curved brim."},

  /* ---- Catalog expansion (placeholder imagery — real photos to be added) ---- */
  {id:"rl-parachute-cargo-shorts", name:"Parachute Cargo Shorts", cat:"Shorts", price:78, was:0, color:"Slate Grey", tag:"NEW", rating:4.7, reviews:34, sizes:["S","M","L","XL","XXL"], oos:["XL"], photos:["rl-parachute-cargo-shorts-front.jpg","rl-parachute-cargo-shorts-side.jpg","rl-parachute-cargo-shorts-back.jpg","rl-parachute-cargo-shorts-detail.jpg"], story:["The Parachute Cargo Shorts channel utility-tech energy with a lightweight crinkle-nylon build and a billowy, adjustable leg. Toggle cords at the waist and hem let you cinch the volume from loose to tapered in seconds.","Zip cargo pockets, bungee toggles and a matte slate finish give them a modern, functional edge that layers over any silhouette. Water-resistant and packable, they travel as well as they wear."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Relaxed parachute fit","Adjustable bungee toggle waist and hems","Zip cargo pockets","Elasticated drawcord waist","Matte, water-resistant crinkle nylon","Reserved LA woven tab","100% nylon"], desc:"Lightweight nylon parachute shorts with cinch toggles, zip cargo pockets, and a relaxed drop. Built for movement."},
  {id:"rl-mesh-panel-shorts", name:"Mesh Panel Basketball Shorts", cat:"Shorts", price:52, was:0, color:"Navy / White", tag:"", rating:4.6, reviews:57, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-mesh-panel-shorts-front.jpg","rl-mesh-panel-shorts-side.jpg","rl-mesh-panel-shorts-back.jpg","rl-mesh-panel-shorts-detail.jpg"], story:["The Mesh Panel Basketball Shorts take a court-ready staple and give it an elevated, oversized cut. Breathable mesh panels and contrast piping deliver retro athletic energy with a modern drop.","An elasticated drawcord waist and longer length keep them comfortable and easy to style, on or off the court. Cut from a quick-dry poly mesh that moves and breathes."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Oversized athletic fit","Longer length","Breathable mesh panels","Contrast side piping","Elasticated drawcord waist","Reserved LA woven tab","100% quick-dry polyester"], desc:"Breathable double-layer mesh shorts with contrast side panels and an above-the-knee cut. A warm-weather staple."},
  {id:"rl-raw-hem-denim-shorts", name:"Raw-Hem Denim Shorts", cat:"Shorts", price:64, was:78, color:"Mid Blue", tag:"SALE", rating:4.5, reviews:41, sizes:["S","M","L","XL"], oos:[], photos:["rl-raw-hem-denim-shorts-front.jpg","rl-raw-hem-denim-shorts-side.jpg","rl-raw-hem-denim-shorts-back.jpg","rl-raw-hem-denim-shorts-detail.jpg"], story:["The Raw-Hem Denim Shorts keep it clean and classic — a mid-blue wash in a relaxed straight cut that falls to the knee. Minimal detailing lets the denim and the raw hem do the talking.","A hand-cut, un-hemmed leg opening frays naturally over time, while five-pocket styling and antique rivets keep them grounded in heritage denim. Built from pure cotton denim that breaks in beautifully."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed straight fit","Falls to the knee","Hand-cut raw hem","Five-pocket construction","Antique rivets","Reserved LA woven tab","100% cotton denim"], desc:"Rigid denim shorts chopped to a raw, frayed hem with a relaxed knee-length fit and vintage whiskering."},
  {id:"rl-stacked-flare-jeans", name:"Stacked Flare Jeans", cat:"Denim", price:132, was:0, color:"Washed Blue", tag:"NEW", rating:4.8, reviews:63, sizes:["S","M","L","XL","XXL"], oos:["S"], photos:["rl-stacked-flare-jeans-front.jpg","rl-stacked-flare-jeans-side.jpg","rl-stacked-flare-jeans-back.jpg","rl-stacked-flare-jeans-detail.jpg"], story:["The Stacked Flare Jeans are built to stack, cut extra-long with a flared leg that pools and breaks over your sneakers. A light washed-blue finish with a subtle tonal floral pattern keeps them elevated yet versatile.","The flare opens from the knee for a dramatic, elongating line, finished with five-pocket styling and antique rivets. Cut from a cotton denim with a hint of stretch for movement."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Flared leg","Extra-long stacked length","Light washed-blue with tonal floral pattern","Opens from the knee","Five-pocket construction","Reserved LA woven tab","Cotton denim with stretch"], desc:"Extra-long flared denim built to stack over your sneakers, with subtle whiskering and a mid-rise waist."},
  {id:"rl-carpenter-wideleg-jeans", name:"Carpenter Wide-Leg Jeans", cat:"Denim", price:126, was:0, color:"Washed Olive", tag:"", rating:4.7, reviews:48, sizes:["S","M","L","XL","XXL"], oos:["M","L"], photos:["rl-carpenter-wideleg-jeans-front.jpg","rl-carpenter-wideleg-jeans-side.jpg","rl-carpenter-wideleg-jeans-back.jpg","rl-carpenter-wideleg-jeans-detail.jpg"], story:["The Carpenter Wide-Leg Jeans fuse workwear function with a modern wide leg, cut roomy through the thigh in a washed-olive overdye with a subtle tonal monogram. Utility detailing gives them genuine jobsite heritage.","A hammer loop, side utility pocket, patch pockets and reinforced seams bring the carpenter DNA, while the wide leg keeps the look current. Built from heavy washed cotton twill made to last."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 32-inch waist — wears size M", features:["Wide-leg fit","Mid-rise","Washed-olive overdye with tonal monogram","Hammer loop and side utility pocket","Patch pockets and reinforced seams","Reserved LA woven tab","100% cotton twill"], desc:"Washed-olive carpenter jeans with a hammer loop, utility pockets, and a true wide-leg drape. Heavy cotton twill that breaks in."},
  {id:"rl-coated-flare-jeans", name:"Coated Skinny-Flare Jeans", cat:"Denim", price:128, was:0, color:"Coated Black", tag:"", rating:4.6, reviews:29, sizes:["S","M","L","XL"], oos:[], photos:["rl-coated-flare-jeans-front.jpg","rl-coated-flare-jeans-side.jpg","rl-coated-flare-jeans-back.jpg","rl-coated-flare-jeans-detail.jpg"], story:["The Coated Skinny-Flare Jeans bring a sleek, rock-leaning edge with a glossy coated-black finish, a subtle tonal crackle texture and a skinny-through-the-thigh, flared-at-the-hem cut. The waxed coating gives them a leather-like sheen.","Sitting low on the waist and slim through the leg before flaring out below the knee, they read sharp and elongating. Cut from a coated cotton-stretch denim that hugs and moves with you."], model:"Model is 175cm / 5ft 9in — wears size M", features:["Skinny-flare fit","Low-rise","Glossy coated-black finish with tonal crackle","Flares below the knee","Five-pocket styling","Reserved LA woven tab","Coated cotton-stretch denim"], desc:"Waxed-coating denim with a slim top block and dramatic flared hem for a sleek, leather-like finish."},
  {id:"rl-patchwork-repair-denim", name:"Patchwork Repair Denim", cat:"Denim", price:144, was:168, color:"Vintage Patch", tag:"SALE", rating:4.8, reviews:52, sizes:["S","M","L","XL","XXL"], oos:["S"], photos:["rl-patchwork-repair-denim-front.jpg","rl-patchwork-repair-denim-side.jpg","rl-patchwork-repair-denim-back.jpg","rl-patchwork-repair-denim-detail.jpg"], story:["The Patchwork Repair Denim celebrates imperfection, piecing contrasting mid-indigo panels and visible repairs into a one-of-a-kind relaxed wide-leg jean. A subtle tonal monogram runs through the base wash, and every pair carries its own map of patches and stitching.","Exposed repair stitching, layered patches, blown-out rips and a carpenter hammer loop give it a genuinely artisanal, upcycled feel. Built from heavyweight cotton denim for durability under all that detail."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 32-inch waist — wears size M", features:["Relaxed wide-leg fit","Mid-indigo with tonal monogram","Contrast patchwork panels","Visible repair stitching and rips","Carpenter hammer loop","Reserved LA woven tab","100% cotton denim"], desc:"Repair-detailed denim pieced from contrasting washes with visible darning and a relaxed straight leg."},
  {id:"rl-waxed-trucker-jacket", name:"Waxed Trucker Jacket", cat:"Jackets", price:168, was:0, color:"Waxed Black", tag:"NEW", rating:4.8, reviews:37, sizes:["S","M","L","XL"], oos:[], photos:["rl-waxed-trucker-jacket-hero.jpg"], story:["The Waxed Trucker Jacket reworks a denim-jacket classic in waxed black cotton for a moody, weather-ready finish. The wax coating develops natural wear marks and character over time.","Classic trucker lines — chest flap pockets, button front and adjustable waist tabs — stay true to the original, upgraded with a subtle sheen. Built from waxed cotton canvas that only looks better with age."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Classic trucker fit","Waxed cotton finish","Button-front closure","Chest flap pockets","Adjustable waist tabs","Reserved LA woven label","Waxed cotton canvas"], desc:"Structured trucker in waxed cotton with a broken-in sheen, chest flap pockets, and a boxy modern cut."},
  {id:"rl-nylon-ma1-bomber", name:"Nylon MA-1 Bomber", cat:"Jackets", price:148, was:0, color:"Sage", tag:"", rating:4.7, reviews:44, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-nylon-ma1-bomber-hero.jpg"], story:["The Nylon MA-1 Bomber pays homage to the military flight jacket in a clean sage nylon. A timeless silhouette that anchors everything from denim to cargos.","The signature utility sleeve pocket, ribbed trims and reversible-orange lining detail keep it authentic, while the lightweight fill works year-round. Cut from smooth water-resistant nylon."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Classic MA-1 fit","Utility zip sleeve pocket","Ribbed collar, cuffs and hem","Full-zip front","Lightweight insulation","Reserved LA woven label","Water-resistant nylon"], desc:"Classic MA-1 silhouette in matte nylon with a utility sleeve pocket and ribbed collar, cuffs and hem."},
  {id:"rl-hooded-puffer-jacket", name:"Hooded Puffer Jacket", cat:"Jackets", price:198, was:0, color:"Jet Black", tag:"NEW", rating:4.9, reviews:51, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-hooded-puffer-jacket-hero.jpg"], story:["The Hooded Puffer Jacket delivers proper cold-weather warmth in a sleek jet-black finish. Baffled channels and a fitted hood give it a clean, modern outline.","A full-zip front, high collar and zip hand pockets seal out the chill, while the lightweight fill packs serious warmth without bulk. Built from a matte water-resistant shell with insulated fill."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Regular fit","Fitted, insulated hood","Baffled quilt construction","Full-zip front with high collar","Zip hand pockets","Reserved LA woven label","Water-resistant shell, insulated fill"], desc:"Oversized baffle puffer with a high funnel hood and matte finish. Warm, roomy, and built for layering."},
  {id:"rl-suede-western-jacket", name:"Suede Western Jacket", cat:"Jackets", price:214, was:0, color:"Tobacco", tag:"", rating:4.7, reviews:22, sizes:["S","M","L","XL"], oos:["L"], photos:["rl-suede-western-jacket-hero.jpg"], story:["The Suede Western Jacket brings a warm tobacco tone and classic Western yokes for a rich, elevated layer. Soft suede gives it a luxe, tactile finish.","Front and back yokes, snap-button closure and slanted chest pockets nod to Western heritage, cut in a modern, slightly relaxed shape. Made from a soft faux-suede with a smooth lining."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Slightly relaxed fit","Western front and back yokes","Snap-button closure","Slanted chest pockets","Warm tobacco tone","Reserved LA woven label","Soft faux-suede"], desc:"Faux-suede western jacket with yoke seams, snap front, and a soft brushed hand. A refined layering piece."},
  {id:"rl-distressed-denim-trucker", name:"Distressed Denim Trucker", cat:"Jackets", price:156, was:184, color:"Faded Indigo", tag:"SALE", rating:4.6, reviews:39, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-distressed-denim-trucker-hero.jpg"], story:["The Distressed Denim Trucker is a faded-indigo take on the icon, worked over with hand-placed distressing and abrasions for authentic vintage character. It reads like a jacket you have owned for years.","Classic trucker detailing — chest flap pockets, button front and waist tabs — meets rips, fades and repaired sections. Built from rigid cotton denim that softens with wear."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Classic trucker fit","Faded indigo wash","Hand-placed distressing and repairs","Button-front closure","Chest flap pockets","Reserved LA woven label","100% cotton denim"], desc:"Vintage-washed denim trucker with hand-done distressing and a cropped, boxy fit."},
  {id:"rl-nylon-coach-jacket-2", name:"Nylon Coach Jacket", cat:"Jackets", price:118, was:0, color:"Black", tag:"", rating:4.6, reviews:47, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-nylon-coach-jacket-2-hero.jpg"], story:["The Nylon Coach Jacket keeps it clean and versatile — a matte-black shell in the timeless coach silhouette. Minimal branding lets it slot into any rotation.","A snap-button front, spread collar and lined body make it an easy throw-on layer for changing weather. Cut from a lightweight water-resistant nylon with a soft lining."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Regular fit","Matte-black nylon shell","Snap-button front","Spread collar","Side hand pockets","Reserved LA woven label","Water-resistant nylon, lined"], desc:"Lightweight water-repellent coach jacket with a snap front and elasticated cuffs. An everyday shell."},
  {id:"rl-fleece-work-jacket", name:"Fleece-Lined Work Jacket", cat:"Jackets", price:176, was:0, color:"Washed Olive", tag:"", rating:4.8, reviews:31, sizes:["S","M","L","XL","XXL"], oos:["L"], photos:["rl-fleece-work-jacket-hero.jpg"], story:["The Fleece-Lined Work Jacket is built for cold jobsite mornings and city winters alike, pairing a washed-olive cotton shell with a cozy sherpa lining. Rugged looks, genuine warmth.","Chest and hand pockets, a button front and a corduroy collar bring workwear function, while the sherpa lining seals in heat. Made from a heavy washed cotton with a plush fleece interior."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size M", features:["Regular workwear fit","Washed-olive cotton shell","Sherpa fleece lining","Corduroy collar","Chest and hand pockets","Reserved LA woven label","Cotton shell, sherpa lining"], desc:"Cotton-canvas chore jacket lined in sherpa fleece, with triple-needle stitching and utility pockets."},
  {id:"rl-nylon-parachute-pants", name:"Nylon Parachute Pants", cat:"Bottoms", price:98, was:0, color:"Black", tag:"NEW", rating:4.7, reviews:66, sizes:["S","M","L","XL","XXL"], oos:["S"], photos:["rl-nylon-parachute-pants-hero.jpg"], story:["The Nylon Parachute Pants bring full utility-tech energy, cut billowy in matte-black nylon with adjustable toggles to shape the leg. Cinch them in or let them balloon.","Bungee toggle hems, cargo pockets and an elasticated waist make them as functional as they are eye-catching. Built from lightweight water-resistant ripstop nylon."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Relaxed parachute fit","Bungee toggle hems","Cargo pockets","Elasticated drawcord waist","Matte water-resistant finish","Reserved LA woven tab","100% ripstop nylon"], desc:"Billowy nylon parachute pants with adjustable toggles at the waist and hem. Techwear-ready volume."},
  {id:"rl-flared-track-pants", name:"Flared Track Pants", cat:"Bottoms", price:82, was:0, color:"Charcoal", tag:"", rating:4.6, reviews:58, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-flared-track-pants-hero.jpg"], story:["The Flared Track Pants remix a retro sport staple with a modern flared leg and a clean charcoal finish. Sporty roots, elevated shape.","Side stripes, an elasticated drawcord waist and a flared hem give them dynamic, leg-lengthening movement. Cut from a smooth poly-blend track fabric."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Flared leg","Elasticated drawcord waist","Contrast side stripes","Zip ankle detail","Side pockets","Reserved LA woven tab","Smooth poly-blend"], desc:"Jersey track pants with a stacked flare leg and side stripe. Elastic waist with a drawcord."},
  {id:"rl-wool-wideleg-trousers", name:"Wide-Leg Wool Trousers", cat:"Bottoms", price:112, was:0, color:"Grey Marl", tag:"", rating:4.7, reviews:33, sizes:["S","M","L","XL"], oos:["XL"], photos:["rl-wool-wideleg-trousers-hero.jpg"], story:["The Wide-Leg Wool Trousers bring quiet-luxury tailoring to the lineup, cut wide in a soft grey-marl wool blend. Elevated enough for the office, relaxed enough for the weekend.","A clean waistband, pressed crease and wide leg keep the lines sharp and elongating. Made from a brushed wool blend with a comfortable drape."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 32-inch waist — wears size M", features:["Wide-leg tailored fit","Grey-marl wool blend","Pressed front crease","Clean waistband","Slant side pockets","Reserved LA woven tab","Brushed wool blend"], desc:"Drapey wool-blend trousers with front pleats and a wide, fluid leg. Smart-casual done street."},
  {id:"rl-ripstop-cargo-jogger", name:"Ripstop Cargo Jogger", cat:"Bottoms", price:88, was:0, color:"Field Olive", tag:"BEST SELLER", rating:4.8, reviews:121, sizes:["S","M","L","XL","XXL"], oos:["L"], photos:["rl-ripstop-cargo-jogger-hero.jpg"], story:["The Ripstop Cargo Jogger blends cargo utility with a tapered jogger cut in a versatile field olive. Function up top, clean taper down low.","Bellowed cargo pockets, an elasticated drawcord waist and ribbed ankle cuffs make them practical and easy to move in. Built from durable cotton ripstop."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 31-inch waist — wears size M", features:["Tapered jogger fit","Bellowed cargo pockets","Elasticated drawcord waist","Ribbed ankle cuffs","Field-olive finish","Reserved LA woven tab","100% cotton ripstop"], desc:"Tapered ripstop joggers with bellowed cargo pockets and adjustable hem toggles. Everyday utility."},
  {id:"rl-balloon-sweatpants", name:"Balloon-Fit Sweatpants", cat:"Bottoms", price:84, was:0, color:"Ash Grey", tag:"", rating:4.6, reviews:44, sizes:["S","M","L","XL","XXL"], oos:["M"], photos:["rl-balloon-sweatpants-hero.jpg"], story:["The Balloon-Fit Sweatpants play with proportion, ballooning through the leg before gathering at the ankle for a bold, sculptural silhouette. Comfort meets statement shape.","An elasticated drawcord waist and gathered cuffs hold the volume in place, while brushed fleece keeps them soft. Made from a heavyweight cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Balloon fit","Gathered ankle cuffs","Elasticated drawcord waist","Brushed-back fleece","Side pockets","Reserved LA woven tab","Cotton-blend fleece"], desc:"Heavyweight fleece sweatpants with a rounded balloon leg and ribbed cuff. Cozy, sculptural comfort."},
  {id:"rl-heavyweight-box-hoodie", name:"Heavyweight Box-Fit Hoodie", cat:"Hoodies", price:98, was:0, color:"Bone", tag:"BEST SELLER", rating:4.9, reviews:143, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-heavyweight-box-hoodie-hero.jpg"], story:["The Heavyweight Box-Fit Hoodie is our essential heavyweight, cut boxy and cropped-ish in a clean bone tone. Structured, premium and built to hold its shape.","A dense 450gsm fleece, dropped shoulders and ribbed trims give it that expensive, structured drape. Made from heavyweight brushed cotton fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Boxy, structured fit","Dropped shoulders","Heavyweight 450gsm fleece","Kangaroo pocket","Ribbed cuffs and hem","Reserved LA woven label","Heavyweight cotton fleece"], desc:"420gsm brushed-back fleece in a boxy, cropped fit with dropped shoulders and a double-lined hood."},
  {id:"rl-washed-zip-hoodie", name:"Washed Zip-Up Hoodie", cat:"Hoodies", price:108, was:0, color:"Washed Black", tag:"NEW", rating:4.7, reviews:62, sizes:["S","M","L","XL","XXL"], oos:["M","L"], photos:["rl-washed-zip-hoodie-hero.jpg"], story:["The Washed Zip-Up Hoodie brings a lived-in, garment-washed finish in a soft washed black. The wash gives it faded, worn-in character from the first wear.","A full-zip front, lined hood and roomy pockets make it an easy everyday layer. Cut from a garment-washed cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Regular fit","Garment-washed finish","Full-zip front","Double-lined hood","Split kangaroo pocket","Reserved LA woven label","Cotton-blend fleece"], desc:"Garment-washed full-zip hoodie with matte hardware and a heavyweight, lived-in hand."},
  {id:"rl-acid-wash-hoodie", name:"Acid-Wash Pullover Hoodie", cat:"Hoodies", price:104, was:0, color:"Acid Grey", tag:"", rating:4.7, reviews:48, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-acid-wash-hoodie-hero.jpg"], story:["The Acid-Wash Pullover Hoodie leads with a bold acid wash that maps unique light-and-dark texture across the body. No two pieces wear the same.","A heavyweight build, oversized cut and ribbed trims keep it grounded despite the loud finish. Made from an acid-washed cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized fit","Bold acid wash","Heavyweight fleece","Kangaroo pocket","Ribbed cuffs and hem","Reserved LA woven label","Cotton-blend fleece"], desc:"Acid-washed heavyweight fleece with a faded, one-of-one finish and a kangaroo pocket."},
  {id:"rl-raw-edge-hoodie", name:"Distressed Raw-Edge Hoodie", cat:"Hoodies", price:112, was:0, color:"Vintage Black", tag:"", rating:4.6, reviews:37, sizes:["S","M","L","XL"], oos:["XL"], photos:["rl-raw-edge-hoodie-hero.jpg"], story:["The Distressed Raw-Edge Hoodie goes grunge, with a vintage-black wash, raw exposed seams and hand-placed distressing. Built to look like a decade-old favorite.","Raw-cut edges, thumbhole cuffs and light thrashing add character, while the heavyweight fleece keeps it warm. Cut from a washed cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized fit","Vintage-black wash","Raw, exposed edges","Hand-placed distressing","Kangaroo pocket","Reserved LA woven label","Cotton-blend fleece"], desc:"Deconstructed hoodie with raw exposed seams, subtle distressing and an oversized drape."},
  {id:"rl-cropped-hoodie", name:"Cropped Boxy Hoodie", cat:"Hoodies", price:88, was:0, color:"Cement", tag:"", rating:4.6, reviews:41, sizes:["S","M","L","XL"], oos:["XL"], photos:["rl-cropped-hoodie-hero.jpg"], story:["The Cropped Boxy Hoodie takes a shorter, boxier cut in a soft cement tone for a modern, layered silhouette. Made to sit high and stack over longer tees.","A cropped hem, dropped shoulders and ribbed trims keep the proportions sharp. Made from a midweight brushed cotton fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Cropped boxy fit","Dropped shoulders","Cement tone","Kangaroo pocket","Ribbed cropped hem","Reserved LA woven label","Brushed cotton fleece"], desc:"Shortened, boxy hoodie with a wide ribbed hem. Layers clean over longline tees."},
  {id:"rl-sherpa-hoodie", name:"Sherpa-Lined Hoodie", cat:"Hoodies", price:124, was:0, color:"Chocolate", tag:"NEW", rating:4.8, reviews:29, sizes:["S","M","L","XL","XXL"], oos:["M","XL"], photos:["rl-sherpa-hoodie-hero.jpg"], story:["The Sherpa-Lined Hoodie brings serious cold-weather comfort, lining a rich chocolate shell with plush sherpa fleece. Cozy warmth without losing the streetwear silhouette.","A lined hood, heavyweight body and ribbed trims seal in heat, while the sherpa adds texture and warmth. Cut from a heavy cotton shell with a sherpa interior."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized fit","Plush sherpa lining","Chocolate tone","Lined hood","Kangaroo pocket","Reserved LA woven label","Cotton shell, sherpa lining"], desc:"Heavy hoodie lined with plush sherpa through the body and hood. Serious cold-weather warmth."},
  {id:"rl-half-zip-hoodie", name:"Half-Zip Hoodie", cat:"Hoodies", price:96, was:0, color:"Slate", tag:"", rating:4.6, reviews:35, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-half-zip-hoodie-hero.jpg"], story:["The Half-Zip Hoodie updates the pullover with a clean half-zip funnel neck in a versatile slate tone. A sharper, more elevated take on the everyday hoodie.","The half-zip lets you adjust the collar, while a heavyweight fleece and ribbed trims keep it warm and structured. Made from a brushed cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Regular fit","Half-zip funnel neck","Slate tone","Heavyweight fleece","Kangaroo pocket","Reserved LA woven label","Cotton-blend fleece"], desc:"Mock-neck half-zip in brushed fleece with a clean, minimal front and a boxy fit."},
  {id:"rl-contrast-stitch-hoodie", name:"Contrast-Stitch Hoodie", cat:"Hoodies", price:102, was:0, color:"Off White", tag:"", rating:4.5, reviews:26, sizes:["S","M","L","XL"], oos:["XL"], photos:["rl-contrast-stitch-hoodie-hero.jpg"], story:["The Contrast-Stitch Hoodie adds a subtle design detail with bold contrast stitching across an off-white body. Clean base, standout seams.","Exposed contrast seams, a heavyweight build and ribbed trims give it an elevated, considered look. Cut from a brushed cotton-blend fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized fit","Off-white body","Contrast exposed stitching","Heavyweight fleece","Kangaroo pocket","Reserved LA woven label","Cotton-blend fleece"], desc:"Inside-out construction with exposed contrast stitching and a heavyweight loopback interior."},
  {id:"rl-heavy-fleece-hoodie", name:"Heavy Fleece Pullover Hoodie", cat:"Hoodies", price:94, was:112, color:"Faded Navy", tag:"SALE", rating:4.7, reviews:73, sizes:["S","M","L","XL","XXL"], oos:[], photos:["rl-heavy-fleece-hoodie-hero.jpg"], story:["The Heavy Fleece Pullover Hoodie is a faded-navy essential built around a dense, ultra-soft fleece. Warmth and structure in a timeless pullover.","Dropped shoulders, a lined hood and ribbed trims deliver that premium heavyweight drape. Made from a heavyweight brushed cotton fleece."], model:"Model is 185cm / 6ft 1in, 75kg / 165lbs, 40-inch chest — wears size L for an oversized fit", features:["Oversized fit","Faded-navy tone","Heavyweight brushed fleece","Double-lined hood","Kangaroo pocket","Reserved LA woven label","Heavyweight cotton fleece"], desc:"Everyday pullover in dense brushed fleece with a roomy hood and ribbed trims."},
  {id:"rl-nylon-5panel-cap", name:"Nylon 5-Panel Cap", cat:"Headwear", price:36, was:0, color:"Black", tag:"NEW", rating:4.7, reviews:52, sizes:["OS"], oos:[], photos:["rl-nylon-5panel-cap-hero.jpg"], story:["The Nylon 5-Panel Cap brings a technical, outdoorsy edge in matte black nylon. Clean, lightweight and built for everyday wear.","The five-panel crown, flat-ish brim and adjustable strap keep it sporty and modern, in a water-resistant shell. Made from lightweight nylon."], model:"One size — adjustable strap back", features:["Five-panel crown","Flat-ish brim","Matte-black nylon","Water-resistant shell","Adjustable strap back","Reserved LA woven tab"], desc:"Lightweight nylon 5-panel with a flat brim and hidden zip pocket. Adjustable strap back."},
  {id:"rl-trucker-mesh-cap", name:"Trucker Mesh Cap", cat:"Headwear", price:34, was:0, color:"Stone / Black", tag:"", rating:4.6, reviews:63, sizes:["OS"], oos:[], photos:["rl-trucker-mesh-cap-hero.jpg"], story:["The Trucker Mesh Cap keeps things breezy with a stone front and black mesh back for that classic trucker feel. Retro roots, everyday wearability.","A structured foam front, curved brim and snapback closure deliver authentic trucker styling. Made from a cotton-front, poly-mesh-back build."], model:"One size — snapback closure", features:["Structured trucker crown","Breathable mesh back","Curved brim","Stone / black colourway","Snapback closure","Reserved LA woven tab"], desc:"Foam-front trucker with a breathable mesh back and structured crown. Snapback closure."},
  {id:"rl-fisherman-beanie", name:"Fisherman Beanie", cat:"Headwear", price:30, was:0, color:"Charcoal", tag:"BEST SELLER", rating:4.8, reviews:98, sizes:["OS"], oos:[], photos:["rl-fisherman-beanie-hero.jpg"], story:["The Fisherman Beanie takes the short, snug docker silhouette in a versatile charcoal. A minimal, clean-lined beanie that sits high on the head.","The tight rib knit hugs the head for a neat, no-slouch fit, finished with a small folded cuff. Made from a soft merino-blend rib knit."], model:"One size — fits most; the rib knit stretches to shape", features:["Short docker fit","Tight rib knit","Charcoal tone","Neat folded cuff","Reserved LA woven tab","Merino-blend knit"], desc:"Short-cuff fisherman beanie in a tight rib knit. Sits high, warm and stretchy."},
  {id:"rl-reversible-bucket-hat", name:"Reversible Bucket Hat", cat:"Headwear", price:42, was:0, color:"Camo / Black", tag:"", rating:4.6, reviews:37, sizes:["OS"], oos:[], photos:["rl-reversible-bucket-hat-hero2.jpg"], story:["The Reversible Bucket Hat gives you two looks in one — camo on one side, solid black on the other. Flip it to match any fit.","A classic bucket silhouette with a stitched brim works on both sides, packing flat for travel. Made from a cotton-blend twill, fully reversible."], model:"One size — reversible", features:["Classic bucket silhouette","Fully reversible: camo / black","Stitched brim","Packable","Reserved LA woven tab","Cotton-blend twill"], desc:"Two hats in one — camo on one side, solid on the other, with embroidered eyelets."},
  {id:"rl-knit-balaclava", name:"Knit Balaclava Hood", cat:"Headwear", price:38, was:0, color:"Black", tag:"", rating:4.5, reviews:24, sizes:["OS"], oos:[], photos:["rl-knit-balaclava-hero2.jpg"], story:["The Knit Balaclava Hood brings a modern, moody layer in solid black, covering the head and neck with a fitted face opening. Equal parts function and statement.","The stretch rib knit hugs close for warmth without bulk, and layers under hoods and hats. Made from a soft acrylic-blend stretch knit."], model:"One size — stretch knit", features:["Fitted balaclava hood","Stretch rib knit","Solid black","Warm, low-bulk build","Reserved LA woven tab","Acrylic-blend knit"], desc:"Ribbed knit balaclava that wears as a hood or neck gaiter. A winter techwear essential."},
];

/* attach images: real photos when provided, else generated placeholder */
PRODUCTS.forEach(p=>{
  if(p.photos && p.photos.length){
    p.gallery = p.photos.map(f=>"assets/products/"+f);
    p.img = p.gallery[0];
    return;
  }
  const bg = CAT_BG[p.cat] || "#17150f";
  p.img = phSvg(p.color + " · " + p.cat, p.name.split(" ").slice(0,2).join(" "), {bg});
  p.gallery = [
    p.img,
    phSvg("Front View", p.name.split(" ")[0], {bg}),
    phSvg("Back View", "Back", {bg}),
    phSvg("Detail", "Detail", {bg})
  ];
});

function fmt(n){ return "$" + Number(n).toFixed(Number.isInteger(n)?0:2); }
function getProduct(id){ return PRODUCTS.find(p=>p.id===id); }
